arg.o: arg.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h argcl.h
brk.o: brk.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h brkcl.h
dreg.o: dreg.cc dregcl.h hwcl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h memcl.h ../eventcl.h ../errorcl.h uccl.h \
 ../pobjt.h brkcl.h stackcl.h varcl.h itabcl.h uccl_instructions.h
guiobj.o: guiobj.cc guiobjcl.h ../ddconfig.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h
hw.o: hw.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h ../pobjcl.h \
 ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h memcl.h \
 ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h hwcl.h
itab.o: itab.cc itabcl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../stypes.h
itsrc.o: itsrc.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h itsrccl.h uccl.h memcl.h
iwrap.o: iwrap.cc iwrap.h uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h hwcl.h guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h memcl.h \
 ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h
mem.o: mem.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h ../utils.h ../fiocl.h memcl.h
obsolete.o: obsolete.cc
port_hw.o: port_hw.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h port_hwcl.h hwcl.h
serial_hw.o: serial_hw.cc ../utils.h ../stypes.h ../ddconfig.h \
 ../charscl.h ../fiocl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../globals.h \
 ../appcl.h ../optioncl.h argcl.h ../pobjcl.h ../stypes.h simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h \
 uccl.h ../pobjt.h hwcl.h guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h memcl.h ../eventcl.h ../errorcl.h \
 brkcl.h stackcl.h varcl.h itabcl.h uccl_instructions.h argcl.h \
 serial_hwcl.h hwcl.h
sim.o: sim.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h ../utils.h ../fiocl.h \
 ../cmd.src/cmd_execcl.h simifcl.h uccl.h hwcl.h
simif.o: simif.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h \
 ../pobjcl.h ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h \
 guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 memcl.h ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h simifcl.h uccl.h hwcl.h
stack.o: stack.cc uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../pobjt.h hwcl.h guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h memcl.h ../eventcl.h ../errorcl.h \
 brkcl.h stackcl.h varcl.h itabcl.h uccl_instructions.h
test_mem_speed.o: test_mem_speed.cc memcl.h ../ddconfig.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 guiobjcl.h ../eventcl.h ../errorcl.h ../pobjcl.h ../stypes.h hwcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h uccl.h ../pobjt.h brkcl.h stackcl.h varcl.h \
 itabcl.h uccl_instructions.h
uc.o: uc.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h argcl.h ../pobjcl.h \
 ../stypes.h simcl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h guiobjcl.h uccl.h ../pobjt.h hwcl.h guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h memcl.h \
 ../eventcl.h ../errorcl.h brkcl.h stackcl.h varcl.h itabcl.h \
 uccl_instructions.h argcl.h ../utils.h ../fiocl.h ../cmd.src/cmd_uccl.h \
 ../cmd.src/cmd_bpcl.h ../cmd.src/cmd_getcl.h ../cmd.src/cmd_setcl.h \
 ../cmd.src/cmd_infocl.h ../cmd.src/cmd_timercl.h ../cmd.src/cmd_statcl.h \
 ../cmd.src/cmd_memcl.h ../cmd.src/cmd_execcl.h uccl.h itsrccl.h memcl.h \
 simifcl.h hwcl.h vcdcl.h
var.o: var.cc varcl.h ../pobjcl.h ../ddconfig.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 memcl.h ../stypes.h guiobjcl.h ../eventcl.h ../errorcl.h
vcd.o: vcd.cc ../ddconfig.h ../stypes.h ../ddconfig.h ../utils.h \
 ../stypes.h ../charscl.h ../fiocl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../globals.h ../appcl.h ../optioncl.h argcl.h ../pobjcl.h simcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h guiobjcl.h \
 uccl.h ../pobjt.h hwcl.h guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h memcl.h ../eventcl.h ../errorcl.h \
 brkcl.h stackcl.h varcl.h itabcl.h uccl_instructions.h argcl.h \
 ../appcl.h argcl.h simcl.h vcdcl.h hwcl.h
