device.o: device.c device.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h pcode.h
gen.o: gen.c device.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h gen.h main.h \
 pcode.h ralloc.h pcoderegs.h glue.h ../../support/util/dbuf_string.h \
 ../../support/util/dbuf.h
genarith.o: genarith.c ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h gen.h main.h \
 pcode.h ralloc.h pcoderegs.h
glue.o: glue.c glue.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h \
 ../../support/util/dbuf_string.h ../../support/util/dbuf.h device.h \
 gen.h main.h pcode.h ralloc.h pcoderegs.h
main.o: main.c ../common.h ../SDCCglobl.h ../SDCCset.h ../../sdccconf.h \
 ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h ../SDCCast.h \
 ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h ../SDCCy.h \
 ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h \
 ../../support/util/dbuf_string.h ../../support/util/dbuf.h \
 ../SDCCmacro.h device.h gen.h main.h pcode.h ralloc.h pcoderegs.h glue.h \
 peeph.rul
pcode.o: pcode.c device.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h gen.h main.h \
 pcode.h ralloc.h pcoderegs.h pcodeflow.h
pcodeflow.o: pcodeflow.c pcodeflow.h pcode.h ../common.h ../SDCCglobl.h \
 ../SDCCset.h ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h \
 ../../support/util/dbuf.h ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h \
 ../SDCCattr.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h \
 ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h \
 ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h ../SDCCopt.h \
 ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h ../SDCCicode.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h ../port.h ../SDCCargs.h \
 ../../support/util/newalloc.h
pcodepeep.o: pcodepeep.c pcode.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h pcodeflow.h \
 ralloc.h pcoderegs.h
pcoderegs.o: pcoderegs.c main.h pcoderegs.h ../common.h ../SDCCglobl.h \
 ../SDCCset.h ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h \
 ../../support/util/dbuf.h ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h \
 ../SDCCattr.h ../SDCCval.h ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h \
 ../SDCClabel.h ../SDCCBBlock.h ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h \
 ../SDCCdflow.h ../SDCClrange.h ../SDCCptropt.h ../SDCCopt.h \
 ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h ../SDCCicode.h ../SDCCdebug.h \
 ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h ../port.h ../SDCCargs.h \
 ../../support/util/newalloc.h pcode.h pcodeflow.h ralloc.h
ralloc.o: ralloc.c device.h ../common.h ../SDCCglobl.h ../SDCCset.h \
 ../../sdccconf.h ../SDCCerr.h ../SDCCmem.h ../../support/util/dbuf.h \
 ../SDCCast.h ../SDCCsymt.h ../SDCChasht.h ../SDCCattr.h ../SDCCval.h \
 ../SDCCy.h ../SDCCbitv.h ../SDCCicode.h ../SDCClabel.h ../SDCCBBlock.h \
 ../SDCCloop.h ../SDCCcse.h ../SDCCcflow.h ../SDCCdflow.h ../SDCClrange.h \
 ../SDCCptropt.h ../SDCCopt.h ../SDCCglue.h ../SDCCpeeph.h ../SDCCgen.h \
 ../SDCCicode.h ../SDCCdebug.h ../SDCCutil.h ../SDCCasm.h ../SDCCsystem.h \
 ../port.h ../SDCCargs.h ../../support/util/newalloc.h gen.h main.h \
 pcode.h ralloc.h pcoderegs.h
