g11p0.o: g11p0.cc g11p0.h ../stypes.h ../ddconfig.h
g11p18.o: g11p18.cc g11p18.h ../stypes.h ../ddconfig.h
g11p1a.o: g11p1a.cc g11p1a.h ../stypes.h ../ddconfig.h
g11pcd.o: g11pcd.cc g11pcd.h ../stypes.h ../ddconfig.h
glob11.o: glob11.cc glob11.h ../stypes.h ../ddconfig.h
m68hc11.o: m68hc11.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h ../sim.src/dregcl.h g11p0.h g11p18.h g11p1a.h \
 g11pcd.h wraps.h ../sim.src/uccl.h m68hc11cl.h ../sim.src/memcl.h \
 ../m6800.src/m6800cl.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h \
 ../m6800.src/decode.h ../sim.src/iwrap.h d11p0.h d11p18.h hc18.h
simm68hc11.o: simm68hc11.cc glob11.h ../stypes.h ../ddconfig.h \
 simm68hc11cl.h ../sim.src/simcl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h m68hc11cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h \
 ../sim.src/iwrap.h d11p0.h d11p18.h hc18.h
sm68hc11.o: sm68hc11.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h glob11.h simm68hc11cl.h
wraps.o: wraps.cc ../sim.src/iwrap.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h m68hc11cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h d11p0.h \
 d11p18.h hc18.h
