tinibios.o: tinibios.c ../../include/tinibios.h ../../include/ds80c390.h \
 ../../include/time.h ../../include/stdio.h ../../include/stdarg.h \
 ../../include/sdcc-lib.h ../../include/asm/mcs51/features.h
memcpyx.o: memcpyx.c ../../include/string.h
i2c390.o: i2c390.c ../../include/tinibios.h ../../include/ds80c390.h \
 ../../include/time.h
rtc390.o: rtc390.c ../../include/tinibios.h ../../include/ds80c390.h \
 ../../include/time.h ../../include/stdio.h ../../include/stdarg.h \
 ../../include/sdcc-lib.h ../../include/asm/mcs51/features.h \
 ../../include/ctype.h
putchar.o: putchar.c ../../include/tinibios.h ../../include/ds80c390.h \
 ../../include/time.h ../../include/stdio.h ../../include/stdarg.h \
 ../../include/sdcc-lib.h ../../include/asm/mcs51/features.h
gptr_cmp.o: gptr_cmp.c
atomic_flag_test_and_set.o: atomic_flag_test_and_set.c
atomic_flag_clear.o: atomic_flag_clear.c
