glob.o: glob.cc glob.h ../stypes.h ../ddconfig.h
ialu.o: ialu.cc m6800cl.h ../ddconfig.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h decode.h \
 ../sim.src/iwrap.h
ibranch.o: ibranch.cc m6800cl.h ../ddconfig.h ../sim.src/uccl.h \
 ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h decode.h \
 ../sim.src/iwrap.h
imove.o: imove.cc m6800cl.h ../ddconfig.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h decode.h \
 ../sim.src/iwrap.h
inst.o: inst.cc m6800cl.h ../ddconfig.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h decode.h \
 ../sim.src/iwrap.h
irq.o: irq.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h irqcl.h \
 m6800cl.h ../sim.src/uccl.h ../sim.src/memcl.h decode.h \
 ../sim.src/iwrap.h
m6800.o: m6800.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h ../sim.src/dregcl.h ../motorola.src/ciacl.h \
 ../sim.src/uccl.h ../sim.src/serial_hwcl.h ../motorola.src/piacl.h \
 ../sim.src/hwcl.h ../sim.src/port_hwcl.h glob.h irqcl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h m6800cl.h ../sim.src/memcl.h \
 decode.h ../sim.src/iwrap.h
simm6800.o: simm6800.cc simm6800cl.h ../sim.src/simcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h m6800cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h decode.h ../sim.src/iwrap.h
sm6800.o: sm6800.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h simm6800cl.h
