dis.o: dis.cc glob12.h ../stypes.h ../ddconfig.h m68hc12cl.h \
 ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h \
 ../sim.src/iwrap.h ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h \
 ../m68hc11.src/hc18.h
glob12.o: glob12.cc glob12.h ../stypes.h ../ddconfig.h
glob.o: glob.cc glob.h ../stypes.h ../ddconfig.h ../sim.src/iwrap.h \
 ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h
hcwrap.o: hcwrap.cc glob12.h ../stypes.h ../ddconfig.h hcwrapcl.h \
 m68hc12cl.h ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/memcl.h \
 ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h ../m6800.src/decode.h ../sim.src/iwrap.h \
 ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h ../m68hc11.src/hc18.h \
 wdecls.h wfills.h wdefs.h
ialu.o: ialu.cc m68hc12cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h \
 ../sim.src/iwrap.h ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h \
 ../m68hc11.src/hc18.h
ibranch.o: ibranch.cc m68hc12cl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h \
 ../sim.src/iwrap.h ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h \
 ../m68hc11.src/hc18.h
imov.o: imov.cc m68hc12cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h \
 ../sim.src/iwrap.h ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h \
 ../m68hc11.src/hc18.h
iother.o: iother.cc m68hc12cl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h ../m6800.src/decode.h \
 ../sim.src/iwrap.h ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h \
 ../m68hc11.src/hc18.h
m68hc12.o: m68hc12.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h ../sim.src/dregcl.h ../m68hc11.src/wraps.h \
 ../sim.src/uccl.h hcwrapcl.h glob12.h m68hc12cl.h ../sim.src/memcl.h \
 ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h ../m6800.src/decode.h ../sim.src/iwrap.h \
 ../m68hc11.src/d11p0.h ../m68hc11.src/d11p18.h ../m68hc11.src/hc18.h \
 wdecls.h wfills.h
simm68hc12.o: simm68hc12.cc glob.h ../stypes.h ../ddconfig.h \
 ../sim.src/iwrap.h ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h simm68hc12cl.h ../sim.src/simcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/argcl.h m68hc12cl.h ../sim.src/uccl.h ../sim.src/memcl.h \
 ../m68hc11.src/m68hc11cl.h ../m6800.src/m6800cl.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h ../m6800.src/decode.h ../m68hc11.src/d11p0.h \
 ../m68hc11.src/d11p18.h ../m68hc11.src/hc18.h
sm68hc12.o: sm68hc12.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h glob.h ../sim.src/iwrap.h simm68hc12cl.h
