glob.o: glob.cc glob.h ../stypes.h ../ddconfig.h ../sim.src/iwrap.h \
 ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h
ialu.o: ialu.cc mos6502cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h
ibranch.o: ibranch.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h mos6502cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h
imove.o: imove.cc mos6502cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h
inst.o: inst.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 mos6502cl.h ../sim.src/uccl.h ../sim.src/memcl.h decode.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h
irq.o: irq.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h irqcl.h ../sim.src/hwcl.h mos6502cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h
mos6502.o: mos6502.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../globals.h \
 ../appcl.h ../utils.h ../fiocl.h ../sim.src/dregcl.h glob.h \
 ../sim.src/iwrap.h irqcl.h ../sim.src/hwcl.h mos6502cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h
mos6510.o: mos6510.cc ../sim.src/port_hwcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../charscl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../cmd.src/newcmdcl.h ../ddconfig.h ../pobjcl.h \
 ../optioncl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/cmdutil.h \
 ../sim.src/hwcl.h ../stypes.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdcl.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 mos6510cl.h mos6502cl.h ../sim.src/uccl.h ../sim.src/memcl.h decode.h \
 ../sim.src/itsrccl.h ../sim.src/itsrccl.h port10cl.h ../sim.src/hwcl.h
mos65c02.o: mos65c02.cc glob.h ../stypes.h ../ddconfig.h \
 ../sim.src/iwrap.h ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h mos65c02cl.h mos6502cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h decc02.h
mos65c02s.o: mos65c02s.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h glob.h \
 ../sim.src/iwrap.h mos65c02scl.h mos65c02cl.h mos6502cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h decc02.h decc02s.h
mos65ce02.o: mos65ce02.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h mos65ce02cl.h \
 mos65c02scl.h mos65c02cl.h mos6502cl.h ../sim.src/uccl.h \
 ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h ../sim.src/itsrccl.h \
 decc02.h decc02s.h
port10.o: port10.cc port10cl.h ../sim.src/hwcl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h
simmos6502.o: simmos6502.cc simmos6502cl.h ../sim.src/simcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h mos6502cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h decode.h ../sim.src/itsrccl.h \
 ../sim.src/itsrccl.h mos6510cl.h mos65c02cl.h decc02.h mos65c02scl.h \
 decc02s.h mos65ce02cl.h glob.h ../sim.src/iwrap.h
smos6502.o: smos6502.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h simmos6502cl.h glob.h ../sim.src/iwrap.h
