disass.o: disass.cc f8cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 glob.h ../sim.src/iwrap.h decode.h
f8.o: f8.cc ../utils.h ../stypes.h ../ddconfig.h ../charscl.h ../fiocl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/dregcl.h \
 ../sim.src/hwcl.h ../stypes.h ../pobjcl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 f8cl.h ../sim.src/uccl.h glob.h ../sim.src/iwrap.h decode.h
glob.o: glob.cc f8cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 glob.h ../sim.src/iwrap.h decode.h
ialu.o: ialu.cc f8cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 glob.h ../sim.src/iwrap.h decode.h
ibranch.o: ibranch.cc f8cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 glob.h ../sim.src/iwrap.h decode.h
imove.o: imove.cc f8cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 glob.h ../sim.src/iwrap.h decode.h
inst.o: inst.cc f8cl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 glob.h ../sim.src/iwrap.h decode.h
sf8.o: sf8.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h f8cl.h ../sim.src/uccl.h glob.h ../sim.src/iwrap.h \
 decode.h simf8cl.h
simf8.o: simf8.cc simf8cl.h ../sim.src/simcl.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 f8cl.h ../sim.src/uccl.h glob.h ../sim.src/iwrap.h decode.h
