clock.o: clock.cc clockcl.h ../sim.src/hwcl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h
glob.o: glob.cc glob.h ../stypes.h ../ddconfig.h
p1516.o: p1516.cc ../sim.src/dregcl.h ../sim.src/hwcl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h glob.h portcl.h \
 ../sim.src/port_hwcl.h uartcl.h ../sim.src/uccl.h \
 ../sim.src/serial_hwcl.h clockcl.h ../sim.src/hwcl.h p1516cl.h \
 ../sim.src/memcl.h
p2223.o: p2223.cc glob.h ../stypes.h ../ddconfig.h pmon.h p2223cl.h \
 p1516cl.h ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/memcl.h
pmon.o: pmon.cc pmon.h ../stypes.h ../ddconfig.h
port.o: port.cc portcl.h ../sim.src/port_hwcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../charscl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../pobjcl.h ../optioncl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/cmdutil.h ../sim.src/hwcl.h \
 ../stypes.h ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h
simp1516.o: simp1516.cc simp1516cl.h ../sim.src/simcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h p1516cl.h \
 ../sim.src/uccl.h ../sim.src/memcl.h p2223cl.h glob.h
sp1516.o: sp1516.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h simp1516cl.h glob.h
uart.o: uart.cc ../ddconfig.h ../sim.src/argcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../stypes.h \
 ../sim.src/itsrccl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h \
 ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/itsrccl.h uartcl.h \
 ../sim.src/uccl.h ../sim.src/serial_hwcl.h
