gen.o: gen.c
main.o: main.c ../port.h ../SDCCicode.h ../SDCCbitv.h ../SDCCset.h \
 ../SDCCargs.h ../SDCCpeeph.h ../SDCCgen.h ../SDCCicode.h \
 ../../support/util/dbuf.h
ralloc.o: ralloc.c
ralloc2.o: ralloc2.cc
