7fwrap.o: 7fwrap.cc rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h 7fwrap.h \
 ../sim.src/iwrap.h
ddwrap.o: ddwrap.cc rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h ddwrap.h \
 ../sim.src/iwrap.h
edwrap.o: edwrap.cc rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h edwrap.h \
 ../sim.src/iwrap.h
glob.o: glob.cc glob.h ../stypes.h ../ddconfig.h ../sim.src/iwrap.h \
 ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h
gp0m3.o: gp0m3.cc gp0m3.h ../stypes.h ../ddconfig.h
gp0m4.o: gp0m4.cc gp0m4.h ../stypes.h ../ddconfig.h
gpddm3.o: gpddm3.cc gpddm3.h ../stypes.h ../ddconfig.h
gpddm4.o: gpddm4.cc gpddm4.h ../stypes.h ../ddconfig.h
gpedm3a.o: gpedm3a.cc gpedm3a.h ../stypes.h ../ddconfig.h
gpedm3.o: gpedm3.cc gpedm3.h ../stypes.h ../ddconfig.h
gpedm4.o: gpedm4.cc gpedm4.h ../stypes.h ../ddconfig.h
ialu.o: ialu.cc rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h r3kacl.h \
 dpedm3a.h r3kcl.h r2kcl.h r4kcl.h dp0m4.h dpedm4.h dpddm4.h
ibranch.o: ibranch.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h rxkcl.h \
 ../sim.src/uccl.h rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h \
 dpedm3.h dpddm3.h r4kcl_instructions.h dd_instructions.h \
 ed_instructions.h r3kacl.h dpedm3a.h r3kcl.h r2kcl.h r4kcl.h dp0m4.h \
 dpedm4.h dpddm4.h
imove.o: imove.cc glob.h ../stypes.h ../ddconfig.h ../sim.src/iwrap.h \
 ../sim.src/uccl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h rxkcl.h \
 ../sim.src/uccl.h rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h \
 dpedm3.h dpddm3.h r4kcl_instructions.h dd_instructions.h \
 ed_instructions.h r4kcl.h r3kacl.h dpedm3a.h r3kcl.h r2kcl.h dp0m4.h \
 dpedm4.h dpddm4.h
inst.o: inst.cc rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h r3kacl.h \
 dpedm3a.h r3kcl.h r2kcl.h r4kcl.h dp0m4.h dpedm4.h dpddm4.h
r2k.o: r2k.cc r2kcl.h rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h
r3ka.o: r3ka.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h glob.h \
 ../sim.src/iwrap.h gp0m3.h gpddm3.h gpedm3.h gpedm3a.h r3kacl.h \
 dpedm3a.h r3kcl.h r2kcl.h rxkcl.h ../sim.src/uccl.h rmemcl.h rtypes.h \
 ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h
r3k.o: r3k.cc r3kcl.h r2kcl.h rxkcl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h
r4k.o: r4k.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h r4kwrap.h r4kcl.h r3kacl.h dpedm3a.h r3kcl.h \
 r2kcl.h rxkcl.h ../sim.src/uccl.h rmemcl.h rtypes.h ../sim.src/memcl.h \
 decode.h dp0m3.h dpedm3.h dpddm3.h r4kcl_instructions.h \
 dd_instructions.h ed_instructions.h dp0m4.h dpedm4.h dpddm4.h 7fwrap.h \
 ../sim.src/iwrap.h glob.h gp0m3.h gp0m4.h gpddm3.h gpedm3a.h gpddm4.h \
 gpedm3.h gpedm4.h
r4kwrap.o: r4kwrap.cc r4kwrap.h r4kcl.h r3kacl.h dpedm3a.h r3kcl.h \
 r2kcl.h rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h rmemcl.h rtypes.h \
 ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h dp0m4.h \
 dpedm4.h dpddm4.h
r5k.o: r5k.cc r5kcl.h r4kcl.h r3kacl.h dpedm3a.h r3kcl.h r2kcl.h rxkcl.h \
 ../sim.src/uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h rmemcl.h rtypes.h \
 ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h dp0m4.h \
 dpedm4.h dpddm4.h
r6k.o: r6k.cc r6kcl.h r5kcl.h r4kcl.h r3kacl.h dpedm3a.h r3kcl.h r2kcl.h \
 rxkcl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h ../pobjcl.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../ddconfig.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/uccl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h rmemcl.h rtypes.h \
 ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h dp0m4.h \
 dpedm4.h dpddm4.h
rmem.o: rmem.cc rmemcl.h rtypes.h ../sim.src/memcl.h ../ddconfig.h \
 ../stypes.h ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h \
 ../charscl.h ../sim.src/guiobjcl.h ../eventcl.h ../errorcl.h ../pobjcl.h \
 ../stypes.h
rxk.o: rxk.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h ../sim.src/dregcl.h glob.h ../sim.src/iwrap.h \
 gp0m3.h gpedm3.h gpddm3.h rmemcl.h rtypes.h ../sim.src/memcl.h ddwrap.h \
 edwrap.h rxkcl.h ../sim.src/uccl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h
simrxk.o: simrxk.cc simrxkcl.h ../sim.src/simcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h r6kcl.h r5kcl.h \
 r4kcl.h r3kacl.h dpedm3a.h r3kcl.h r2kcl.h rxkcl.h ../sim.src/uccl.h \
 rmemcl.h rtypes.h ../sim.src/memcl.h decode.h dp0m3.h dpedm3.h dpddm3.h \
 r4kcl_instructions.h dd_instructions.h ed_instructions.h dp0m4.h \
 dpedm4.h dpddm4.h
srxk.o: srxk.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h glob.h ../sim.src/iwrap.h simrxkcl.h
