apppblaze.o: apppblaze.cc ../ddconfig.h ../i_string.h ../ddconfig.h \
 ../utils.h ../stypes.h ../charscl.h ../fiocl.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h apppblazecl.h ../appcl.h ../optioncl.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../globals.h \
 ../appcl.h ../cmd.src/cmdutil.h ../cmd.src/cmd_confcl.h \
 ../cmd.src/cmd_showcl.h ../cmd.src/cmd_getcl.h ../cmd.src/cmd_setcl.h
cmdpblaze.o: cmdpblaze.cc ../sim.src/simcl.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 pblazecl.h ../sim.src/uccl.h regspblaze.h interruptcl.h portidcl.h \
 inputportcl.h ../globals.h ../appcl.h ../optioncl.h ../sim.src/argcl.h \
 outputportcl.h instcl.h stackcl.h cmdpblazecl.h
glob.o: glob.cc ../stypes.h ../ddconfig.h glob.h regspblaze.h \
 ../ddconfig.h
inputport.o: inputport.cc pblazecl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 regspblaze.h interruptcl.h portidcl.h inputportcl.h ../globals.h \
 ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/argcl.h outputportcl.h instcl.h stackcl.h
inst.o: inst.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../sim.src/memcl.h glob.h pblazecl.h ../sim.src/uccl.h regspblaze.h \
 interruptcl.h portidcl.h inputportcl.h outputportcl.h instcl.h stackcl.h \
 pblazemac.h
interrupt.o: interrupt.cc ../sim.src/itsrccl.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../stypes.h ../sim.src/uccl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/itsrccl.h \
 pblazecl.h ../sim.src/uccl.h regspblaze.h interruptcl.h portidcl.h \
 inputportcl.h ../globals.h ../appcl.h ../optioncl.h ../sim.src/argcl.h \
 ../sim.src/simcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/argcl.h outputportcl.h instcl.h \
 stackcl.h
outputport.o: outputport.cc pblazecl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 regspblaze.h interruptcl.h portidcl.h inputportcl.h ../globals.h \
 ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/argcl.h outputportcl.h instcl.h stackcl.h tinyxml.h tinystr.h
pblaze.o: pblaze.cc ../ddconfig.h ../i_string.h ../ddconfig.h tinyxml.h \
 tinystr.h ../globals.h ../stypes.h ../appcl.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../sim.src/argcl.h ../pobjcl.h \
 ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h ../optioncl.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h ../sim.src/dregcl.h ../cmd.src/cmd_uccl.h \
 pblazecl.h ../sim.src/uccl.h regspblaze.h interruptcl.h portidcl.h \
 inputportcl.h outputportcl.h instcl.h stackcl.h glob.h pblazemac.h \
 cmdpblazecl.h
portid.o: portid.cc pblazecl.h ../sim.src/uccl.h ../stypes.h \
 ../ddconfig.h ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 regspblaze.h interruptcl.h portidcl.h inputportcl.h ../globals.h \
 ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/argcl.h outputportcl.h instcl.h stackcl.h
simpblaze.o: simpblaze.cc simpblazecl.h ../sim.src/simcl.h ../pobjcl.h \
 ../ddconfig.h ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../gui.src/guicl.h \
 ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h \
 ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h pblazecl.h \
 ../sim.src/uccl.h regspblaze.h interruptcl.h portidcl.h inputportcl.h \
 ../globals.h ../appcl.h ../optioncl.h ../sim.src/argcl.h outputportcl.h \
 instcl.h stackcl.h glob.h
spblaze.o: spblaze.cc ../appcl.h ../ddconfig.h ../pobjcl.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
 ../pobjcl.h ../stypes.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
 ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h ../sim.src/guiobjcl.h \
 ../cmd.src/newcmdposixcl.h ../fiocl.h ../cmd.src/cmdutil.h \
 ../sim.src/memcl.h ../eventcl.h ../errorcl.h ../sim.src/brkcl.h \
 ../sim.src/stackcl.h ../sim.src/varcl.h ../sim.src/itabcl.h \
 ../sim.src/uccl_instructions.h ../sim.src/argcl.h ../globals.h \
 ../appcl.h ../utils.h ../fiocl.h simpblazecl.h glob.h
stack.o: stack.cc pblazecl.h ../sim.src/uccl.h ../stypes.h ../ddconfig.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 regspblaze.h interruptcl.h portidcl.h inputportcl.h ../globals.h \
 ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
 ../gui.src/guicl.h ../gui.src/ifcl.h ../sim.src/guiobjcl.h \
 ../sim.src/argcl.h outputportcl.h instcl.h stackcl.h
