glob.o: glob.cc glob.h ../stypes.h ../ddconfig.h
inst.o: inst.cc glob.h ../stypes.h ../ddconfig.h xacl.h ../sim.src/uccl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../ddconfig.h \
 ../cmd.src/newcmdcl.h ../optioncl.h ../pobjcl.h ../stypes.h \
 ../cmd.src/commandcl.h ../cmd.src/newcmdcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/uccl.h ../sim.src/brkcl.h ../sim.src/stackcl.h \
 ../sim.src/varcl.h ../sim.src/itabcl.h ../sim.src/uccl_instructions.h \
 regsxa.h instcl.h inst_gen.cc
inst_gen.o: inst_gen.cc
simxa.o: simxa.cc simxacl.h ../sim.src/simcl.h ../pobjcl.h ../ddconfig.h \
 ../pobjt.h ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 xacl.h ../sim.src/uccl.h regsxa.h instcl.h
sxa.o: sxa.cc ../globals.h ../ddconfig.h ../stypes.h ../appcl.h \
 ../pobjcl.h ../pobjt.h ../eventcl.h ../charscl.h ../optioncl.h \
 ../sim.src/argcl.h ../pobjcl.h ../stypes.h ../sim.src/simcl.h \
 ../cmd.src/newcmdcl.h ../ddconfig.h ../optioncl.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../pobjt.h ../sim.src/hwcl.h \
 ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h ../fiocl.h \
 ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h ../errorcl.h \
 ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../utils.h ../fiocl.h simxacl.h
xa.o: xa.cc ../sim.src/simcl.h ../pobjcl.h ../ddconfig.h ../pobjt.h \
 ../eventcl.h ../charscl.h ../cmd.src/newcmdcl.h ../ddconfig.h \
 ../optioncl.h ../pobjcl.h ../stypes.h ../cmd.src/commandcl.h \
 ../cmd.src/newcmdcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
 ../sim.src/guiobjcl.h ../sim.src/uccl.h ../stypes.h ../pobjt.h \
 ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdposixcl.h \
 ../fiocl.h ../cmd.src/cmdutil.h ../sim.src/memcl.h ../eventcl.h \
 ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h ../sim.src/varcl.h \
 ../sim.src/itabcl.h ../sim.src/uccl_instructions.h ../sim.src/argcl.h \
 ../sim.src/dregcl.h xacl.h ../sim.src/uccl.h regsxa.h instcl.h glob.h
